os:
  - linux
  - osx
language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - indent
install: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew bundle; fi
script:
  - make indent && git diff --exit-code
  - make
