os:
  - linux
  - osx
dist: trusty
sudo: required
language:
  - c
  - cpp
addons:
  apt:
    packages:
    - debian-keyring
    - aria2
    - opencl-headers
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
    brew update;
    brew install aria2 gnupg2;
    fi;
  - mkdir cmake_dist
  - cd cmake_dist
  - |
    binFoldersURI="https://cmake.org/files/"
    binsDevURI=$binFoldersUrl"dev/"
    if [[ $TRAVIS_OS_NAME == "linux" ]];
    then
    cmakeOS=linux;
    fi;
    if [[ $TRAVIS_OS_NAME == "osx" ]];
    then
    cmakeOS=darwin;
    fi;

  - cmakeVer=$(curl $binFoldersURI | grep -iPo "(?<=\"v)(?:\\d+\\.)+\\d+(?=/\")" | sort -rV | head -1)
  - binsUrl=$binFoldersURI"v"$cmakeVer"/"
  - cmakeFileName=$(curl $binsURI"?C=M;O=D" | grep -iPo "(?<=\")cmake-"$cmakeVer"(?:\\.\\d+)+(-gs[a-f\\d]+)?-"$cmakeOS"-x86_64\\.tar\\.gz(?=\")" | head -1)
  - cmakeFullVer=$(echo $cmakeFileName | grep -iPo "(?<=-)$cmakeVer(?:\\.\\d+)+(?=-)") 
  - |
    cmakeURI=$binsURI$cmakeFileName
    cmakeHashsumsURI=$binsURI"cmake-"$cmakeFullVer"-SHA-256.txt"
    cmakeHashsumsSigURI=$cmakeHashsumFile".asc"

  - aria2c -s 5 -o cmake.tar.gz $cmakeURI
  - aria2c -o hashes.txt $hashsumsFileURI
  - aria2c -o hashes.txt.asc $hashsumsSigURI
  -  if [[ "$TRAVIS_OS_NAME" == "linux" ]];
     then
     sudo apt-get remove aria2;
     fi;
     if [[ "$TRAVIS_OS_NAME" == "osx" ]];
     then
     sudo brew remove aria2;
     fi;
  - gpg --recv-keys --keyserver hkp://pgp.mit.edu 34921684
  - gpg --verify hashes.txt.asc
  - grep -i $(sha256sum cmake.tar.gz | grep -i -P "^[0-9a-f]+" -o) hashes.txt
  - tar --restrict -xf cmake.tar.gz
  - mv $(tar -t -f cmake.tar.gz | head -1 | grep -P -o ^.+?(?=/))/* ./
  - rm cmake.tar.gz hashes.txt hashes.txt.asc
  - chmod -R +x bin
  - cd ..
install:
compiler:
  - clang
  - gcc
  - g++
script:
  - mkdir ./build
  - cd build
  - ../cmake_dist/bin/cmake ../
  - make
