<<<<<<< HEAD
=======
before_install:
 - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
>>>>>>> refs/remotes/hashcat/coverity_scan
os:
  - linux
language: c
<<<<<<< HEAD
compiler:
  - clang
  - gcc
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
=======
>>>>>>> refs/remotes/hashcat/coverity_scan
script:
  - make
env:
  global:
   - secure: "EQhY6iBjtU7978g1PBkQLvTnb7EBDLrf7FVBETfYqGTYMNUKn31JP3357gcE9EVSbgq94qMA/A60oa4WqvRUCk+JhqpBrTYPSY19IgRqYpHHmXMGwmCF+kITpITDaiASK+cHHpc1/QXAelOI+ovdQpIcQUCQ1jrzDc1aF6k89qxOW884RwNFZzwqjWP1YCZRaecm6k0J7pKZpbT0oXTmtAFQE3EhP0XZG8JkLIXTGvjg30UHkKNgooeL9c/y2Q7tnua97SKpHtEgZP41Yg6BcWcbWWZPH4WfSIskV4uafhGwbr3IxSLOoiYX4+bOxXiY3GLQU4Qhro81AfcR5c7+mBQwbJPxPtqaeQfv2YGyzXJnyLZqVBZ0yKhKRX/QU7up7+BpVMzAdSmRQvgq2B1Nb2B/p+dKFnkzAS83Y8rpYyOxscRODqbQIPwK3LPZ+0CExbKShIbxWcVhVcQVRMBlh4mblLre463KPCXE4mGMD4TKUxTNat7mq237qzYoA9g3x5uIKWAxNG4ZHyQuvYFT3mfmTDlSLx7f6NtgNLVT1SpIdJDbCqoAAf56P52Eympz+T91Gpc1Ecxr2isKKAQ11myPzLjUNyU3CGA65EUf0V1ghYa9IZcq7H/lnBfyDkwsLbkRad4p3Q7kUNjuo91VqT4bBlrb4AuFf4zbsy+IKe8="
addons:
  coverity_scan:
    project:
      name: "hashcat/hashcat"
      description: "Build submitted via Travis CI"
    notification_email: jens.steube@gmail.com
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
