sudo: required
os:
  - linux
  - osx
language: c
compiler:
  - clang
  - gcc
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
script:
  - ./autogen.sh && ./configure --enable-static --disable-shared --disable-debug CPPFLAGS=-I$(pwd)/deps/OpenCL-Headers/ && make && sudo make install
